version: '2'

services:
  odoo:
    build: .
    image: lambda-is/l10n-macedonia:11.1
    depends_on:
      - db
    ports:
      - "8069:8069"
    links:
      - db
    volumes:
      - attachments:/var/lib/odoo
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=odoo
      - PGUSER=odoo
      - POSTGRES_DB=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  attachments:
    driver: local
  data:
    driver: local
