version: '2'

services:
  odoo:
    image: pollen.hbee.eu/l10n-macedonia:9.0.0.1
    depends_on:
      - db
    ports:
      - "8069:8069"
    links:
      - db
    volumes:
      - attachments:/home/odoo/.local
  db:
    image: pollen.hbee.eu/pgsql:9.5.0
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  attachments:
    driver: local
  data:
    driver: local
